### ISSUE TITLE
Downsampling error

### ISSUE THREAD

**Issue by cnzqy1** [scalableminds/webknossos-cuber#206]
I ran into the following error when I was executing the `wkcuber` command on Windows 10, Python 3.8.2 64-bit. I tried multiple different datasets and got the same error. Could you take a look and see what might be the issue? Thank you!

> 2020-04-27 22:21:13,751 INFO Downsampling mag 2 from mag 1
Traceback (most recent call last):
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\__main__.py", line 86, in <module>
    main(parsed_args)
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\__main__.py", line 59, in main
    downsample_mags_anisotropic(
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\downsampling.py", line 617, in downsample_mags_anisotropic
    downsample_mag(
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\downsampling.py", line 490, in downsample_mag
    downsample(
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\downsampling.py", line 146, in downsample
    source_cube_addresses = cube_addresses(source_wkw_info)
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\utils.py", line 54, in cube_addresses
    wkw_addresses = list(parse_cube_file_name(f) for f in source_wkw.list_files())
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\utils.py", line 54, in <genexpr>
    wkw_addresses = list(parse_cube_file_name(f) for f in source_wkw.list_files())
  File "C:\Users\cnzqy\AppData\Local\Programs\Python\Python38\lib\site-packages\wkcuber\utils.py", line 61, in parse_cube_file_name
    return int(m.group(3)), int(m.group(2)), int(m.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by hotzenklotz** [comment]
@cnzqy1 At a first glance, it looks to be problem with the expected naming convention of the dataset. Do you mind explaining how your data ist structured and named on the file system? 

What command did you use to call the cuber? Thanks for the info.

**Comment by cnzqy1** [comment]
The dataset is an image stack in the format of single-tile 8-bit grayscale tiff images named test_s000.tif - test_s800.tif.

Here is the complete log:
C:\>py -m wkcuber --layer_name color --scale 4,4,4 --name great_dataset source target
2020-04-28 09:11:07,915 INFO Found source files: count=801 size=412x914
2020-04-28 09:11:07,924 INFO Using pool of 16 workers.
2020-04-28 09:11:10,021 INFO Compressing mag 1 in 'target.compress-37b42665-5e68-42a0-968f-af2b2c97d5ae\color\1'
2020-04-28 09:11:10,025 INFO Using pool of 16 workers.
2020-04-28 09:11:14,137 INFO Mag 1 successfully compressed
2020-04-28 09:11:14,183 INFO Downsampling mag 2 from mag 1
Traceback (most recent call last):
(followed by the same error message in the first post)

**Comment by philippotto** [comment]
@cnzqy1 webknossos-cuber is not officially supported on Windows. From your output, I assume that there is a problem due to forward slashes vs. backward slashes. Could you please try to use the cuber under Windows's subsystem for Linux? Here's a tutorial on how to use it: https://devblogs.microsoft.com/commandline/an-in-depth-tutorial-on-linux-development-on-windows-with-wsl-and-visual-studio-code/
Alternatively, a virtual machine with Linux or another computer with a bare-metal installation of Linux would work, too.

**Comment by cnzqy1** [comment]
I can confirm that webknossos-cuber works well on Windows Subsystem for Linux. Thank you very much for your help! I'll close the issue now.
