### ISSUE TITLE
ModuleNotFoundError: No module named 'wkcuber.vendor'

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos-cuber#27]
In the `0.1.4` release, `import wkcuber` fails:

```
>>> import wkcuber
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/__init__.py", line 1, in <module>
    from .cubing import cubing
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/cubing.py", line 19, in <module>
    from .image_readers import image_reader
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/image_readers.py", line 5, in <module>
    from .vendor.dm3 import DM3
ModuleNotFoundError: No module named 'wkcuber.vendor'
```

**Comment by normanrz** [comment]
Please try `0.1.5`

**Comment by georgwiese** [comment]
Working now, thanks :)
