### ISSUE TITLE
wkw.wkw.WKWException: Could not read raw header

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos-cuber#30]
When running `python -m wkcuber.downsampling --layer_name color <dataset> --verbose --jobs 4`, everything goes well, until at some point I get this exception.

What follows is an excerpt of the log. The end is the actual end of the log.

```
INFO:root:Mag 16 succesfully cubed
INFO:root:Downsampling mag 32 from mag 16
DEBUG:root:Found source cubes: count=64 size=(256, 256, 256) min=(0, 0, 0) max=(3, 3, 3)
DEBUG:root:Found target cubes: count=8 size=(256, 256, 256) min=(0, 0, 0) max=(1, 1, 1)
DEBUG:root:Downsampling (0, 0, 0)
DEBUG:root:Downsampling (0, 0, 1)
DEBUG:root:Downsampling (0, 1, 0)
DEBUG:root:Downsampling (0, 1, 1)
ERROR:root:Downsampling of (0, 0, 1) failed with Could not read raw header
DEBUG:root:Downsampling (1, 0, 0)
DEBUG:root:Skipping empty cube (0, 1, 1)
DEBUG:root:Downsampling of (0, 1, 1) took 6.62861705s
DEBUG:root:Downsampling (1, 0, 1)
DEBUG:root:Skipping empty cube (1, 0, 1)
DEBUG:root:Downsampling of (0, 1, 0) took 8.01861262s
DEBUG:root:Downsampling of (1, 0, 0) took 8.01916122s
DEBUG:root:Downsampling (1, 1, 0)
DEBUG:root:Downsampling (1, 1, 1)
DEBUG:root:Downsampling of (0, 0, 0) took 10.45284390s
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/wkw/wkw.py", line 209, in open
    handle = _check_wkw_null(libwkw.dataset_create(root_c, header.to_c()))
  File "/opt/conda/lib/python3.6/site-packages/wkw/wkw.py", line 54, in _check_wkw_null
    _raise_wkw_exception()
  File "/opt/conda/lib/python3.6/site-packages/wkw/wkw.py", line 44, in _raise_wkw_exception
    raise WKWException(error_msg.decode())
wkw.wkw.WKWException: Could not read raw header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/downsampling.py", line 194, in downsample_cube_job
    raise exc
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/downsampling.py", line 168, in downsample_cube_job
    target_wkw_info, pool_get_lock()
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/utils.py", line 30, in open_wkw
    return _open_wkw(info)
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/utils.py", line 24, in _open_wkw
    wkw.Header(np.dtype(info.dtype)),
  File "/opt/conda/lib/python3.6/site-packages/wkw/wkw.py", line 211, in open
    handle = _check_wkw_null(libwkw.dataset_open(root_c))
  File "/opt/conda/lib/python3.6/site-packages/wkw/wkw.py", line 54, in _check_wkw_null
    _raise_wkw_exception()
  File "/opt/conda/lib/python3.6/site-packages/wkw/wkw.py", line 44, in _raise_wkw_exception
    raise WKWException(error_msg.decode())
wkw.wkw.WKWException: Could not read raw header
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/downsampling.py", line 336, in <module>
    int(args.jobs),
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/downsampling.py", line 318, in downsample_mags
    jobs,
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/downsampling.py", line 300, in downsample_mag
    jobs,
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/downsampling.py", line 150, in downsample
    target_cube_xyz,
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/utils.py", line 107, in __exit__
    [f.result() for f in self.futures]
  File "/opt/conda/lib/python3.6/site-packages/wkcuber/utils.py", line 107, in <listcomp>
    [f.result() for f in self.futures]
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
wkw.wkw.WKWException: Could not read raw header
DEBUG:root:Skipping empty cube (1, 1, 1)
DEBUG:root:Downsampling of (1, 0, 1) took 4.16329288s
DEBUG:root:Downsampling of (1, 1, 1) took 4.42877126s
DEBUG:root:Downsampling of (1, 1, 0) took 4.56905389s
```

**Comment by philippotto** [comment]
Let's reopen if this appears again. Might have been fixed by now, since we haven't experienced this in a long time.
