### ISSUE TITLE
Extended test suite fails with WKWException

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos-cuber#357]
When running `tests/scripts/all_tests.sh` I get the following error message:

```
+ python -m wkcuber.convert_image_stack_to_wkw --jobs 2 --batch_size 8 --layer_name color --max_mag 4 --scale 11.24,11.24,25 --name awesome_data --sampling_mode isotropic testdata/tiff testoutput/tiff2
2021-07-23 12:20:10,129 INFO Found source files: count=257 size=265x265
2021-07-23 12:20:10,131 INFO Using pool of 2 workers.
2021-07-23 12:20:10,144 INFO Cubing z=32-39
2021-07-23 12:20:10,144 INFO Cubing z=0-7
2021-07-23 12:20:10,160 ERROR Cubing of z=32-39 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,161 INFO Cubing z=64-71
2021-07-23 12:20:10,161 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32dfcbac0 state=finished raised WKWException>
2021-07-23 12:20:10,164 ERROR Cubing of z=0-7 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,165 INFO Cubing z=96-103
2021-07-23 12:20:10,165 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32debfa30 state=finished raised WKWException>
2021-07-23 12:20:10,169 ERROR Cubing of z=64-71 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,169 INFO Cubing z=128-135
2021-07-23 12:20:10,169 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb1c0 state=finished raised WKWException>
2021-07-23 12:20:10,172 ERROR Cubing of z=96-103 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,172 INFO Cubing z=160-167
2021-07-23 12:20:10,172 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb2e0 state=finished raised WKWException>
2021-07-23 12:20:10,177 ERROR Cubing of z=128-135 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,178 INFO Cubing z=192-199
2021-07-23 12:20:10,178 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb400 state=finished raised WKWException>
2021-07-23 12:20:10,180 ERROR Cubing of z=160-167 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,180 INFO Cubing z=224-231
2021-07-23 12:20:10,181 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb520 state=finished raised WKWException>
2021-07-23 12:20:10,185 ERROR Cubing of z=192-199 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,186 INFO Cubing z=256-256
2021-07-23 12:20:10,186 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb640 state=finished raised WKWException>
2021-07-23 12:20:10,187 ERROR Cubing of z=256-256 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,187 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb880 state=finished raised WKWException>
2021-07-23 12:20:10,187 ERROR Cubing of z=224-231 failed with When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
2021-07-23 12:20:10,188 ERROR A future crashed with an exception: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.. Future: <Future at 0x7fd32decb760 state=finished raised WKWException>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "${HOME}/src/webknossos-cuber/wkcuber/cubing.py", line 249, in cubing_job
    raise exc
  File "${HOME}/src/webknossos-cuber/wkcuber/cubing.py", line 236, in cubing_job
    target_wkw.write([0, 0, z_batch[0] / target_mag.to_array()[2]], buffer)
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/site-packages/wkw/wkw.py", line 214, in write
    _check_wkw(
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/site-packages/wkw/wkw.py", line 49, in _check_wkw
    _raise_wkw_exception()
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/site-packages/wkw/wkw.py", line 44, in _raise_wkw_exception
    raise WKWException(error_msg.decode())
wkw.wkw.WKWException: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "${HOME}/src/webknossos-cuber/wkcuber/convert_image_stack_to_wkw.py", line 101, in <module>
    main(args)
  File "${HOME}/src/webknossos-cuber/wkcuber/convert_image_stack_to_wkw.py", line 58, in main
    bounding_box = cubing(
  File "${HOME}/src/webknossos-cuber/wkcuber/cubing.py", line 351, in cubing
    wait_and_ensure_success(executor.map_to_futures(cubing_job, job_args))
  File "${HOME}/src/webknossos-cuber/wkcuber/utils.py", line 279, in wait_and_ensure_success
    fut.result()
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "${HOME}/usr/miniconda3/envs/webknossos-cuber-dev/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
wkw.wkw.WKWException: When writing compressed files, each file has to be written as a whole. Please pad your data so that all cubes are complete and the write position is block-aligned.
```

Cheers,
Eric

**Comment by rschwanhold** [comment]
I was able to reproduce your problem. There is an easy explanation for this error: I assume that you ran this script before. As a result the dataset `testoutput/tiff2` already exists. This dataset was compressed at the end (after the data was written).

When you were running the test again, an **compressed** dataset already existed. Trying to write to this compressed dataset caused the error.

You can simply delete the dataset `testoutput/tiff2` to get this specific test to work. I recommend that you delete everything in the `testoutput` directory to make sure that similar problems with other test cases are prevented.
